django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

django/polls/urls.py
from django.urls import path, re_path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    # re_path를 사용해 정규 표현식으로 구현
    # re_path(r'^$', views.index, name='index'),
    # re_path(r'(?P<question_id>\d+)/$', views.detail, name='detail'),
    # re_path(r'(?P<question_id>\d+)/results/$', views.results, name='results'),
    # re_path(r'(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
]

django/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        '''
        Question의 게시일자가 현재시각에서 1일 전보다 빠른지, 느린지 를 리턴
        :return:
        '''
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return '{} | {}'.format(
            self.question.question_text,
            self.choice_text,
        )

django/polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect

from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)

    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)

    # render함수가 내부적으로 처리되는 과정
    # template = loader.get_template('polls/index.html')
    # return HttpResponse(template.render(context, template))


def detail(request, question_id):
    # try:
    #     question = Question.objects.get(id=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")

    # 위 try문을 한 줄로 표현한 구문
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }
    return render(request, 'polls/results.html', context)


def vote(request, question_id):
    choice_pk = request.POST['choice']
    choice = Choice.objects.get(pk=choice_pk)
    choice.votes += 1
    choice.save()

    return redirect('polls:results', question_id=question_id)

django/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Polls Detail</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}(id:{{choice.id}})</label>
  <br>
  {% endfor %}
  <input type="submit" value="Vote">
</form>
</body>
</html>

django/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Polls</title>
</head>
<body>
{% if latest_question_list %}
  <ul>
    {% for q in latest_question_list %}
    <li>
      <!--{#<a href="{% url 'detail' question_id=q.pk %}">{{ q.question_text }}</a>#}-->
      <a href="{% url 'polls:detail' question_id=q.pk %}">{{ q.question_text }}</a>
    </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}
</body>
</html>

django/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Vote Results</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question_id=question.id %}">Vote Again?</a>
</body>
</html>